<?php
require_once('../lib/fpdf/fpdf.php');
include '../auth/db.php';
session_start();

$volunteer_id = $_SESSION['volunteer_id'] ?? 1;
$event_id = $_GET['event_id'] ?? 1;

// Fetch data
$query = "
    SELECT v.full_name, e.title, e.event_date
    FROM volunteers v
    JOIN event_attendance a ON v.id = a.volunteer_id_fk
    JOIN events e ON e.event_id = a.event_id_fk
    WHERE v.id = $volunteer_id AND e.event_id = $event_id
";
$res = $conn->query($query);
$data = $res->fetch_assoc() ?? [
    'full_name' => 'Atharva Kapile',
    'title' => 'Community Upliftment Drive',
    'event_date' => '2025-09-12'
];

$name = strtoupper($data['full_name']);
$event = $data['title'];
$date = date('F j, Y', strtotime($data['event_date']));

// Create PDF
$pdf = new FPDF('L', 'mm', 'A4');
$pdf->AddPage();

// --- Colors ---
$primary_color = [0, 82, 155];
$accent_color = [227, 162, 26];
$secondary_color = [30, 64, 124];

$pdf->SetMargins(20, 20, 20);
$pdf->SetAutoPageBreak(false);

// --- Background ---
$pdf->SetFillColor(255, 255, 255);
$pdf->Rect(0, 0, 297, 210, 'F');

// --- Borders ---
$pdf->SetDrawColor(...$accent_color);
$pdf->SetLineWidth(4);
$pdf->Rect(10, 10, 277, 190);

$pdf->SetDrawColor(...$primary_color);
$pdf->SetLineWidth(1.5);
$pdf->Rect(20, 20, 257, 170);

// --- Logo ---
$logo_width = 60;
$pdf->Image('../assets/logos.png', ($pdf->GetPageWidth() - $logo_width)/2, 25, $logo_width);

// --- Certificate Title ---
$pdf->Ln(50);
$pdf->SetFont('Times', 'B', 32);
$pdf->SetTextColor(...$secondary_color);
$pdf->Cell(0, 12, 'CERTIFICATE OF APPRECIATION', 0, 1, 'C');

// Underline
$pdf->SetDrawColor(...$accent_color);
$pdf->SetLineWidth(1);
$pdf->Line(70, $pdf->GetY(), 227, $pdf->GetY());

// --- Subtitle ---
$pdf->Ln(10);
$pdf->SetFont('Times', 'I', 16);
$pdf->SetTextColor(100, 100, 100);
$pdf->Cell(0, 10, 'This Certificate is Proudly Presented To', 0, 1, 'C');

// --- Name ---
$pdf->Ln(5);
$pdf->SetFont('Times', 'B', 28);
$pdf->SetTextColor(0, 0, 0);
$pdf->Cell(0, 15, $name, 0, 1, 'C');

// Name underline
$pdf->SetDrawColor(200, 200, 200);
$pdf->SetLineWidth(0.8);
$pdf->Line(70, $pdf->GetY(), 227, $pdf->GetY());

// --- Event Section ---
$pdf->Ln(10);
$pdf->SetFont('Times', '', 14);
$pdf->SetTextColor(60, 60, 60);
$pdf->Cell(0, 7, 'In recognition of your dedicated participation and outstanding contribution to the event', 0, 1, 'C');

// Event name bold & colored
$pdf->SetFont('Times', 'B', 16);
$pdf->SetTextColor(...$primary_color);
$pdf->Cell(0, 7, "\"$event\"", 0, 1, 'C');

// Event date
$pdf->SetFont('Times', 'I', 14);
$pdf->SetTextColor(60, 60, 60);
$pdf->Cell(0, 7, "held on $date.", 0, 1, 'C');

// --- Signature Section (Raised a bit higher) ---
$pdf->Ln(15);
$signature_width = 60;
$signature_height = 30;
$left_x = 50;
$left_y = $pdf->GetY() - 10; // moved signature slightly up
$pdf->Image('../assets/signature2.png', $left_x, $left_y, $signature_width);

// Line under signature
$pdf->SetDrawColor(80, 80, 80);
$pdf->SetLineWidth(0.8);
$pdf->Line($left_x, $left_y + $signature_height, $left_x + $signature_width, $left_y + $signature_height);

// Signature label
$pdf->SetY($left_y + $signature_height + 2);
$pdf->SetX($left_x);
$pdf->SetFont('Times', 'I', 12);
$pdf->SetTextColor(90, 90, 90);
$pdf->Cell($signature_width, 6, "Kashinath Patil - President Imperium Trust", 0, 0, 'C');

// Right - Issued by aligned with signature
$right_x = 180;
$right_y = $left_y + 10; // aligned vertically
$pdf->SetXY($right_x, $right_y);
$pdf->SetFont('Times', 'B', 14);
$pdf->SetTextColor(...$primary_color);
$pdf->Cell(60, 8, "Issued by Imperium Trust", 0, 2, 'C');

$pdf->SetX($right_x);
$pdf->SetFont('Times', 'I', 11);
$pdf->SetTextColor(100, 100, 100);
$pdf->Cell(60, 6, "Creating Impact, Transforming Lives", 0, 2, 'C');

// Line under issued by
$pdf->SetDrawColor(80, 80, 80);
$pdf->SetLineWidth(0.8);
$pdf->Line($right_x, $right_y + 20, $right_x + 60, $right_y + 20);

// --- Footer ---
$pdf->SetY(-20);
$pdf->SetFont('Arial', 'I', 9);
$pdf->SetTextColor(150, 150, 150);
$pdf->Cell(0, 10, 'Generated by Volunteer Management System - Imperium Trust', 0, 0, 'C');

// Output
$pdf->Output('I', "Certificate_" . str_replace(' ', '_', $name) . ".pdf");
?>
